export const AGREGAR_CLIENTE = 'AGREGAR_CLIENTE ';
export const BUSCAR_CLIENTE = 'BUSCAR_CLIENTE';
export const OBTENER_CLIENTES = 'OBTENER_CLIENTES';

export const AGREGAR_EMPLEADO = 'AGREGAR_EMPLEADO';
export const BUSCAR_EMPLEADO_ID = 'BUSCAR_EMPLEADO_ID';
export const BUSCAR_EMPLEADO_NAME = 'BUSCAR_EMPLEADO_NAME';
export const AGREGAR_MANO_OBRA = 'AGREGAR_MANO_OBRA'
export const ELIMINAR_EMPLEADO = 'ELIMINAR_EMPLEADO';
export const EMPLEADO_ACTUAL = 'EMPLEADO_ACTUAL';
export const ACTUALIZAR_DATOS_EMPLEADO = 'ACTUALIZAR_DATOS_EMPLEADO';

export const AGREGAR_MATERIAL  = 'AGREGAR_MATERIAL';
export const AGREGAR_MATERIAL_USO = 'AGREGAR_MATERIAL_USO';
export const ELIMINAR_MATERIAL = 'ELIMINAR_MATERIAL';

export const AGREGAR_GASTOS = 'AGREGAR_GASTOS';
export const ELIMINAR_GASTO = 'ELIMINAR_GASTO'